# Uncomment this line to define a global platform for your project
platform :tvos, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FitnessTV' do

pod "XCDYouTubeKit", "~> 2.5"

end

target 'FitnessTVTests' do

end

target 'FitnessTVUITests' do

end

